# Generated by Django 3.2.4 on 2024-06-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=50)),
                ('itemLocation', models.CharField(max_length=50)),
                ('itemQuantity', models.IntegerField()),
                ('dateAdded', models.DateField()),
            ],
        ),
    ]
